// Build script: compiles Tailwind, bundles only the Lucide icons the app uses,
// and generates als-standalone.html (a single self-contained file, e.g. for SharePoint).
//
//   npm install && npm run build
//
// index.html is the source of truth. Never edit als-standalone.html by hand.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const rel = (...p) => path.join(root, ...p);
const require = createRequire(import.meta.url);

// 1. Tailwind CSS (only the classes used in index.html)
execFileSync(process.execPath, [
  require.resolve('tailwindcss/lib/cli.js'),
  '-c', rel('tools/tailwind.config.cjs'),
  '-i', rel('tools/tailwind.input.css'),
  '-o', rel('vendor/tailwind.css'),
  '--minify',
], { cwd: rel('tools'), stdio: 'inherit' });

// 2. Icons: only those referenced via data-lucide="..." in index.html
const html = fs.readFileSync(rel('index.html'), 'utf8');
const lucide = require('lucide');
const names = [...new Set([...html.matchAll(/data-lucide="([a-z0-9-]+)"/g)].map(m => m[1]))].sort();
const pascal = n => n.split('-').map(p => p[0].toUpperCase() + p.slice(1)).join('');
const icons = {};
for (const n of names) {
  const node = lucide[pascal(n)];
  if (!node) throw new Error(`Unknown Lucide icon: ${n}`);
  icons[n] = node;
}
const iconsJs = `/* Generated by tools/build.mjs from lucide@${require('lucide/package.json').version} (ISC licence). Do not edit. */
(function () {
  var ICONS = ${JSON.stringify(icons)};
  var NS = 'http://www.w3.org/2000/svg';
  function createIcons() {
    document.querySelectorAll('i[data-lucide]').forEach(function (el) {
      var name = el.getAttribute('data-lucide');
      var node = ICONS[name];
      if (!node) return;
      var svg = document.createElementNS(NS, 'svg');
      var attrs = { width: 24, height: 24, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor',
        'stroke-width': 2, 'stroke-linecap': 'round', 'stroke-linejoin': 'round', 'aria-hidden': 'true' };
      for (var k in attrs) svg.setAttribute(k, attrs[k]);
      svg.setAttribute('class', ('lucide lucide-' + name + ' ' + (el.getAttribute('class') || '')).trim());
      node.forEach(function (c) {
        var child = document.createElementNS(NS, c[0]);
        for (var a in c[1]) child.setAttribute(a, c[1][a]);
        svg.appendChild(child);
      });
      el.parentNode.replaceChild(svg, el);
    });
  }
  window.lucide = { createIcons: createIcons };
})();
`;
fs.writeFileSync(rel('vendor/icons.js'), iconsJs);

// 3. Standalone single file
let out = html
  .replace(/<link rel="stylesheet" href="vendor\/([a-z]+)\.css">/g, (_, f) => `<style>\n${fs.readFileSync(rel('vendor', `${f}.css`), 'utf8')}\n</style>`)
  .replace('<script src="vendor/icons.js"></script>', () => `<script>\n${iconsJs}</script>`)
  .replace('<!DOCTYPE html>', '<!DOCTYPE html>\n<!-- GENERATED by tools/build.mjs from index.html — do not edit by hand. -->');
if (/(href|src)="vendor\//.test(out)) throw new Error('Standalone still references vendor/ files');
fs.writeFileSync(rel('als-standalone.html'), out);

const kb = f => (fs.statSync(rel(f)).size / 1024).toFixed(0) + ' KB';
console.log(`Built: vendor/tailwind.css (${kb('vendor/tailwind.css')}), vendor/icons.js (${names.length} icons, ${kb('vendor/icons.js')}), als-standalone.html (${kb('als-standalone.html')})`);
